project:
  type: website

website:
  title: "Sebastián Curaca-Fierro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - illustration.qmd
      - photography.qmd
      - about.qmd


format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

